[2025-06-05 12:20:30] Killing any existing Chrome instances...
[2025-06-05 12:20:33] Starting Python HTTP server...
::1 - - [05/Jun/2025 12:20:40] "GET /test5.html HTTP/1.1" 304 -
::1 - - [05/Jun/2025 12:20:40] code 404, message File not found
::1 - - [05/Jun/2025 12:20:40] "GET /favicon.ico HTTP/1.1" 404 -
[2025-06-05 12:25:05] Killing any existing Chrome instances...
[2025-06-05 12:25:07] Starting Python HTTP server...
::1 - - [05/Jun/2025 12:25:12] "GET /test5.html HTTP/1.1" 304 -
::1 - - [05/Jun/2025 12:25:12] code 404, message File not found
::1 - - [05/Jun/2025 12:25:12] "GET /favicon.ico HTTP/1.1" 404 -
[2025-06-05 12:28:42] Killing any existing Chrome instances...
[2025-06-05 12:28:44] Starting Python HTTP server...
::1 - - [05/Jun/2025 12:28:47] "GET /test5.html HTTP/1.1" 200 -
::1 - - [05/Jun/2025 12:28:47] code 404, message File not found
::1 - - [05/Jun/2025 12:28:47] "GET /favicon.ico HTTP/1.1" 404 -
[2025-06-05 12:29:21] Chrome should now be running in fullscreen kiosk mode!
[2025-06-05 12:29:21] Startup sequence complete. Waiting for user to stop...
[2025-06-05 13:30:36] Killing any existing Chrome instances...
[2025-06-05 13:30:39] Starting Python HTTP server...
::1 - - [05/Jun/2025 13:30:43] "GET /test5.html HTTP/1.1" 200 -
::1 - - [05/Jun/2025 13:30:44] code 404, message File not found
::1 - - [05/Jun/2025 13:30:44] "GET /favicon.ico HTTP/1.1" 404 -
[2025-06-19 10:37:04] Killing any existing Chrome instances...
[2025-06-19 10:37:06] Starting Python HTTP server...
::1 - - [19/Jun/2025 10:37:10] code 404, message File not found
::1 - - [19/Jun/2025 10:37:10] "GET /test5.html HTTP/1.1" 404 -
::1 - - [19/Jun/2025 10:37:10] code 404, message File not found
::1 - - [19/Jun/2025 10:37:10] "GET /favicon.ico HTTP/1.1" 404 -
[2025-06-19 11:16:46] Killing any existing Chrome instances...
[2025-06-19 11:16:48] Starting Python HTTP server...
::1 - - [19/Jun/2025 11:16:52] code 404, message File not found
::1 - - [19/Jun/2025 11:16:52] "GET /test5.html HTTP/1.1" 404 -
::1 - - [19/Jun/2025 11:16:52] code 404, message File not found
::1 - - [19/Jun/2025 11:16:52] "GET /favicon.ico HTTP/1.1" 404 -
[2025-06-19 11:20:56] Killing any existing Chrome instances...
[2025-06-19 11:20:58] Starting Python HTTP server...
::1 - - [19/Jun/2025 11:21:02] "GET /test7.html HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:21:02] "GET /style2.css HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:21:02] "GET /quizLogic.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:21:02] "GET /handTracking.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:21:02] "GET /wordAnimation.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:21:02] "GET /main.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:21:02] "GET /testvid2.mp4 HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:21:02] code 404, message File not found
::1 - - [19/Jun/2025 11:21:02] "GET /favicon.ico HTTP/1.1" 404 -
----------------------------------------
Exception occurred during processing of request from ('::1', 53565, 0, 0)
::1 - - [19/Jun/2025 11:21:04] "GET /testvid2.mp4 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 1320, in finish_request
    self.RequestHandlerClass(request, client_address, self,
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             directory=args.directory)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
    ~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 881, in copyfile
    shutil.copyfileobj(source, outputfile)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 204, in copyfileobj
    fdst_write(buf)
    ~~~~~~~~~~^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 845, in write
    self._sock.sendall(b)
    ~~~~~~~~~~~~~~~~~~^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
[2025-06-19 11:21:09] Chrome should now be running in fullscreen kiosk mode!
[2025-06-19 11:21:09] Startup sequence complete. Waiting for user to stop...
[2025-06-19 11:24:52] Killing any existing Chrome instances...
[2025-06-19 11:24:54] Starting Python HTTP server...
::1 - - [19/Jun/2025 11:24:58] "GET /test7.html HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:24:58] "GET /style2.css HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:24:58] "GET /wordAnimation.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:24:58] "GET /quizLogic.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:24:58] "GET /handTracking.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:24:58] "GET /main.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:24:58] "GET /testvid2.mp4 HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:24:58] code 404, message File not found
::1 - - [19/Jun/2025 11:24:58] "GET /favicon.ico HTTP/1.1" 404 -
----------------------------------------
Exception occurred during processing of request from ('::1', 49994, 0, 0)
::1 - - [19/Jun/2025 11:25:00] "GET /testvid2.mp4 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 1320, in finish_request
    self.RequestHandlerClass(request, client_address, self,
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             directory=args.directory)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
    ~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 881, in copyfile
    shutil.copyfileobj(source, outputfile)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 204, in copyfileobj
    fdst_write(buf)
    ~~~~~~~~~~^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 845, in write
    self._sock.sendall(b)
    ~~~~~~~~~~~~~~~~~~^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('::1', 49997, 0, 0)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 1320, in finish_request
    self.RequestHandlerClass(request, client_address, self,
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             directory=args.directory)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
    ~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 881, in copyfile
    shutil.copyfileobj(source, outputfile)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 204, in copyfileobj
    fdst_write(buf)
    ~~~~~~~~~~^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 845, in write
    self._sock.sendall(b)
    ~~~~~~~~~~~~~~~~~~^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
----------------------------------------
::1 - - [19/Jun/2025 11:25:00] "GET /testvid2.mp4 HTTP/1.1" 200 -
[2025-06-19 11:39:20] Killing any existing Chrome instances...
[2025-06-19 11:39:22] Starting Python HTTP server...
::1 - - [19/Jun/2025 11:39:26] "GET /test7.html HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:39:27] "GET /style2.css HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:39:27] "GET /handTracking.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:39:27] "GET /wordAnimation.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:39:27] "GET /quizLogic.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:39:27] "GET /main.js HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:39:27] "GET /testvid2.mp4 HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:39:27] code 404, message File not found
::1 - - [19/Jun/2025 11:39:27] "GET /favicon.ico HTTP/1.1" 404 -
----------------------------------------
Exception occurred during processing of request from ('::1', 51854, 0, 0)
::1 - - [19/Jun/2025 11:39:28] "GET /testvid2.mp4 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 1320, in finish_request
    self.RequestHandlerClass(request, client_address, self,
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             directory=args.directory)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
    ~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 881, in copyfile
    shutil.copyfileobj(source, outputfile)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 204, in copyfileobj
    fdst_write(buf)
    ~~~~~~~~~~^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 845, in write
    self._sock.sendall(b)
    ~~~~~~~~~~~~~~~~~~^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('::1', 51860, 0, 0)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 1320, in finish_request
    self.RequestHandlerClass(request, client_address, self,
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             directory=args.directory)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
    ~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 881, in copyfile
    shutil.copyfileobj(source, outputfile)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 204, in copyfileobj
    fdst_write(buf)
    ~~~~~~~~~~^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 845, in write
    self._sock.sendall(b)
    ~~~~~~~~~~~~~~~~~~^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
----------------------------------------
::1 - - [19/Jun/2025 11:39:28] "GET /testvid2.mp4 HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:39:44] "GET /testvid2.mp4 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('::1', 52065, 0, 0)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 1320, in finish_request
    self.RequestHandlerClass(request, client_address, self,
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             directory=args.directory)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
    ~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 881, in copyfile
    shutil.copyfileobj(source, outputfile)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 204, in copyfileobj
    fdst_write(buf)
    ~~~~~~~~~~^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 845, in write
    self._sock.sendall(b)
    ~~~~~~~~~~~~~~~~~~^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
::1 - - [19/Jun/2025 11:39:44] "GET /testvid2.mp4 HTTP/1.1" 200 -
::1 - - [19/Jun/2025 11:40:01] "GET /testvid2.mp4 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('::1', 52300, 0, 0)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 1320, in finish_request
    self.RequestHandlerClass(request, client_address, self,
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             directory=args.directory)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
    ~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 881, in copyfile
    shutil.copyfileobj(source, outputfile)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 204, in copyfileobj
    fdst_write(buf)
    ~~~~~~~~~~^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 845, in write
    self._sock.sendall(b)
    ~~~~~~~~~~~~~~~~~~^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
::1 - - [19/Jun/2025 11:40:01] "GET /testvid2.mp4 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('::1', 52302, 0, 0)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 1320, in finish_request
    self.RequestHandlerClass(request, client_address, self,
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             directory=args.directory)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
    ~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 881, in copyfile
    shutil.copyfileobj(source, outputfile)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 204, in copyfileobj
    fdst_write(buf)
    ~~~~~~~~~~^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1520.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 845, in write
    self._sock.sendall(b)
    ~~~~~~~~~~~~~~~~~~^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
